### ISSUE TITLE
Sagemaker

### ISSUE THREAD

**Issue by DJMathijs16** [cosmincatalin/voice-recognition-with-mxnet-and-sagemaker#1]
Hey, is it possible to do the final step, so to see the results and test your data without sagemaker?
Could you explain to us what your code does:
```python
for directory in listdir("data/test"):
    batch = []
    cnt = 0
    total = 0
    detected = 0
    for file in listdir("data/test/{}".format(directory)):
        with open("data/test/{}/{}".format(directory, file), "rb") as audio_file:
            batch.append(base64.b64encode(audio_file.read()).decode("utf-8"))
            cnt += 1
            if cnt == 5:
                binary_json = json.dumps(batch).encode("utf-8")
                response = sagemaker_runtime_client.invoke_endpoint(
                    EndpointName=predictor.endpoint,
                    Body=binary_json,
                    ContentType="application/json",
                    Accept="application/json"
                )["Body"].read()
                individual_predictions = json.loads(response, encoding="utf-8")
                for prediction in individual_predictions:
                    total += 1
                    if prediction == directory:
                        detected += 1
                cnt = 0
                batch = []
    print("""Recordings with {}:
        Total: {}
        Detected: {}
        Accuracy: {:0.2f}
    """.format(directory, str(total), str(detected), detected/total))

And how we could get the same results without sagemaker?
```

**Comment by cosmincatalin** [comment]
Sorry for the late response, but here it goes.  
The piece of code above goes through the folders containing samples of the individual voices (Eg: one Directory for Kimberly, one for Joanna and so on).  For each folder, it takes all the samples out of said folder and encodes them accordingly. Then, it tries to see if it can detect the voice correctly. If the detected voice matches the folder name, than it's a success, otherwise it is a failure.

For this piece of code to work, you do need SageMaker, since you are invoking a SageMaker endpoint. However, you can also choose to pull out the model and load it in a different environment of your choice and make the inference.

I hope this helps, let me know if I can further clarify anything...I'll try to do it faster than in a year's time 😄
